import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const timestamps = {
  createdAt: v.number(),
  updatedAt: v.number(),
};

export default defineSchema({
  companies: defineTable({
    name: v.string(),
    slug: v.string(),
    legalName: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    country: v.string(),
    currency: v.string(),
    timezone: v.string(),
    logoFileId: v.optional(v.string()),
    status: v.union(v.literal("ACTIVE"), v.literal("SUSPENDED"), v.literal("CANCELLED")),
    plan: v.union(v.literal("STARTER"), v.literal("PRO"), v.literal("BUSINESS")),
    ...timestamps,
  }).index("by_slug", ["slug"]),

  users: defineTable({
    authUserId: v.string(),
    companyId: v.id("companies"),
    name: v.string(),
    email: v.string(),
    phone: v.optional(v.string()),
    role: v.union(
      v.literal("OWNER"),
      v.literal("ADMIN"),
      v.literal("MANAGER"),
      v.literal("RECEPTIONIST"),
      v.literal("EXPERIENCE_OPERATOR"),
    ),
    status: v.union(v.literal("ACTIVE"), v.literal("INVITED"), v.literal("DISABLED")),
    ...timestamps,
  }).index("by_authUserId", ["authUserId"]).index("by_companyId", ["companyId"]),

  properties: defineTable({
    companyId: v.id("companies"),
    name: v.string(),
    slug: v.string(),
    description: v.optional(v.string()),
    address: v.optional(v.string()),
    city: v.optional(v.string()),
    country: v.string(),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    timezone: v.string(),
    coverImageId: v.optional(v.string()),
    status: v.union(v.literal("ACTIVE"), v.literal("DRAFT"), v.literal("ARCHIVED")),
    source: v.union(v.literal("MANUAL"), v.literal("HOSTEX")),
    externalHostexId: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_companyId_slug", ["companyId", "slug"]).index("by_externalHostexId", ["externalHostexId"]),

  units: defineTable({
    companyId: v.id("companies"),
    propertyId: v.id("properties"),
    name: v.string(),
    description: v.optional(v.string()),
    unitType: v.union(v.literal("ROOM"), v.literal("APARTMENT"), v.literal("VILLA"), v.literal("HOUSE"), v.literal("CHALET"), v.literal("OTHER")),
    capacity: v.number(),
    adultsCapacity: v.number(),
    childrenCapacity: v.number(),
    bedrooms: v.number(),
    bathrooms: v.number(),
    basePrice: v.number(),
    currency: v.string(),
    status: v.union(v.literal("ACTIVE"), v.literal("DRAFT"), v.literal("ARCHIVED")),
    externalHostexRoomTypeId: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_propertyId", ["propertyId"]).index("by_externalHostexRoomTypeId", ["externalHostexRoomTypeId"]),

  amenities: defineTable({
    companyId: v.id("companies"),
    name: v.string(),
    icon: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]),

  unitAmenities: defineTable({
    companyId: v.id("companies"),
    unitId: v.id("units"),
    amenityId: v.id("amenities"),
    ...timestamps,
  }).index("by_unitId", ["unitId"]).index("by_amenityId", ["amenityId"]),

  guests: defineTable({
    companyId: v.id("companies"),
    firstName: v.string(),
    lastName: v.string(),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    country: v.optional(v.string()),
    language: v.optional(v.string()),
    notes: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_companyId_email", ["companyId", "email"]),

  bookings: defineTable({
    companyId: v.id("companies"),
    propertyId: v.id("properties"),
    unitId: v.id("units"),
    guestId: v.id("guests"),
    source: v.union(v.literal("DIRECT"), v.literal("HOSTEX"), v.literal("MANUAL")),
    externalReservationId: v.optional(v.string()),
    externalChannel: v.optional(v.string()),
    checkIn: v.string(),
    checkOut: v.string(),
    adults: v.number(),
    children: v.number(),
    infants: v.number(),
    currency: v.string(),
    subtotal: v.number(),
    discount: v.number(),
    tax: v.number(),
    extrasTotal: v.number(),
    experiencesTotal: v.number(),
    total: v.number(),
    status: v.union(v.literal("PENDING"), v.literal("CONFIRMED"), v.literal("CHECKED_IN"), v.literal("CHECKED_OUT"), v.literal("CANCELLED"), v.literal("NO_SHOW")),
    notes: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_unitId", ["unitId"]).index("by_guestId", ["guestId"]).index("by_externalReservationId", ["externalReservationId"]),

  bookingItems: defineTable({
    companyId: v.id("companies"),
    bookingId: v.id("bookings"),
    type: v.union(v.literal("ACCOMMODATION"), v.literal("EXPERIENCE"), v.literal("EXTRA"), v.literal("DISCOUNT"), v.literal("TAX"), v.literal("FEE")),
    referenceId: v.optional(v.string()),
    description: v.string(),
    quantity: v.number(),
    unitPrice: v.number(),
    total: v.number(),
    currency: v.string(),
    ...timestamps,
  }).index("by_bookingId", ["bookingId"]),

  experiences: defineTable({
    companyId: v.id("companies"),
    name: v.string(),
    slug: v.string(),
    description: v.string(),
    shortDescription: v.optional(v.string()),
    durationMinutes: v.number(),
    capacity: v.number(),
    price: v.number(),
    currency: v.string(),
    pricingType: v.union(v.literal("PER_PERSON"), v.literal("PER_BOOKING")),
    location: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    coverImageId: v.optional(v.string()),
    status: v.union(v.literal("DRAFT"), v.literal("ACTIVE"), v.literal("PAUSED"), v.literal("ARCHIVED")),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_companyId_slug", ["companyId", "slug"]),

  experienceSchedules: defineTable({
    companyId: v.id("companies"),
    experienceId: v.id("experiences"),
    weekday: v.number(),
    startTime: v.string(),
    endTime: v.string(),
    capacity: v.number(),
    active: v.boolean(),
    ...timestamps,
  }).index("by_experienceId", ["experienceId"]),

  experienceBookings: defineTable({
    companyId: v.id("companies"),
    experienceId: v.id("experiences"),
    bookingId: v.id("bookings"),
    guestId: v.id("guests"),
    date: v.string(),
    startTime: v.string(),
    numberOfParticipants: v.number(),
    unitPrice: v.number(),
    total: v.number(),
    currency: v.string(),
    status: v.union(v.literal("PENDING"), v.literal("CONFIRMED"), v.literal("COMPLETED"), v.literal("CANCELLED"), v.literal("NO_SHOW")),
    notes: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_bookingId", ["bookingId"]).index("by_experienceId_date", ["experienceId", "date"]),

  extras: defineTable({
    companyId: v.id("companies"),
    name: v.string(),
    description: v.optional(v.string()),
    price: v.number(),
    currency: v.string(),
    pricingType: v.union(v.literal("PER_BOOKING"), v.literal("PER_GUEST"), v.literal("PER_NIGHT"), v.literal("PER_DAY")),
    active: v.boolean(),
    ...timestamps,
  }).index("by_companyId", ["companyId"]),

  payments: defineTable({
    companyId: v.id("companies"),
    bookingId: v.id("bookings"),
    provider: v.optional(v.string()),
    externalPaymentId: v.optional(v.string()),
    amount: v.number(),
    currency: v.string(),
    status: v.union(v.literal("PENDING"), v.literal("AUTHORIZED"), v.literal("PAID"), v.literal("FAILED"), v.literal("REFUNDED"), v.literal("PARTIALLY_REFUNDED")),
    method: v.union(v.literal("CARD"), v.literal("BANK_TRANSFER"), v.literal("CASH"), v.literal("MOBILE"), v.literal("OTHER")),
    paidAt: v.optional(v.number()),
    ...timestamps,
  }).index("by_bookingId", ["bookingId"]),

  channelConnections: defineTable({
    companyId: v.id("companies"),
    provider: v.union(v.literal("HOSTEX"), v.literal("BOOKING"), v.literal("AIRBNB"), v.literal("EXPEDIA"), v.literal("VRBO")),
    status: v.union(v.literal("CONNECTED"), v.literal("DISCONNECTED"), v.literal("ERROR"), v.literal("PENDING")),
    accessTokenEncrypted: v.optional(v.string()),
    refreshTokenEncrypted: v.optional(v.string()),
    expiresAt: v.optional(v.number()),
    scope: v.optional(v.string()),
    externalAccountId: v.optional(v.string()),
    lastSyncAt: v.optional(v.number()),
    lastError: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_companyId_provider", ["companyId", "provider"]),

  webhookEvents: defineTable({
    companyId: v.optional(v.id("companies")),
    provider: v.string(),
    eventType: v.string(),
    externalEventId: v.optional(v.string()),
    payloadHash: v.string(),
    payload: v.string(),
    status: v.union(v.literal("RECEIVED"), v.literal("PROCESSING"), v.literal("PROCESSED"), v.literal("FAILED"), v.literal("IGNORED")),
    processedAt: v.optional(v.number()),
    error: v.optional(v.string()),
    ...timestamps,
  }).index("by_payloadHash", ["payloadHash"]).index("by_provider_eventType", ["provider", "eventType"]),

  syncLogs: defineTable({
    companyId: v.id("companies"),
    connectionId: v.id("channelConnections"),
    operation: v.string(),
    entityType: v.string(),
    entityId: v.optional(v.string()),
    status: v.union(v.literal("SUCCESS"), v.literal("FAILED")),
    requestId: v.optional(v.string()),
    errorCode: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    durationMs: v.optional(v.number()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]).index("by_connectionId", ["connectionId"]),

  availability: defineTable({
    companyId: v.id("companies"),
    unitId: v.id("units"),
    date: v.string(),
    status: v.union(v.literal("AVAILABLE"), v.literal("BLOCKED"), v.literal("RESERVED")),
    source: v.union(v.literal("TERA"), v.literal("HOSTEX")),
    bookingId: v.optional(v.id("bookings")),
    ...timestamps,
  }).index("by_unitId_date", ["unitId", "date"]).index("by_companyId_date", ["companyId", "date"]),

  notifications: defineTable({
    companyId: v.id("companies"),
    userId: v.id("users"),
    type: v.string(),
    title: v.string(),
    message: v.string(),
    readAt: v.optional(v.number()),
    ...timestamps,
  }).index("by_userId", ["userId"]),

  auditLogs: defineTable({
    companyId: v.id("companies"),
    userId: v.optional(v.id("users")),
    action: v.string(),
    entityType: v.string(),
    entityId: v.optional(v.string()),
    metadata: v.optional(v.string()),
    ...timestamps,
  }).index("by_companyId", ["companyId"]),
});
